# Run snyk monitor, which will report results to snyk.io
name: Snyk Monitor
on:
  push:
    branches:
      - main
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=the-guardian-cuu --project-name=guardian/manage-frontend --debug --file=./app/yarn.lock
          command: monitor
